name: above_the_bar
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  formz: ^0.4.0
  firebase_auth: ^4.3.0
  firebase_auth_web: ^5.2.10
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.1.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  bloc: ^8.1.1
  path_provider: ^2.0.11
  collection: ^1.15.0
  syncfusion_flutter_charts: ^20.4.53
  const_date_time: ^1.0.2
  pdf: ^3.6.0
  screenshot: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
          weight: 700



