List<String> kExerciseList = [
  "Snatch",
  "Clean & Jerk",
  "Total",
  "Power Snatch",
  "Hang Snatch",
  "Block Snatch",
  "Snatch Deadlift",
  "Clean",
  "Hang Clean",
  "Power Clean",
  "Block Clean",
  "Clean Deadlift",
  "Power Jerk",
  "Jerk from Rack",
  "Jerk from Block",
  "Clean Front Squat Jerk",
  "Push Press",
  "Back Squat",
  "Front Squat",
  "Strict Row",
  "Strict Press",
  "Trunk Hold",
  "Back Hold",
  "Side Hold",
];
