// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8MYxEFUaroFMhUI7az8-A5HaQ-3gewS0',
    appId: '1:216112482967:web:eb1e89fa003b5ace5f37d2',
    messagingSenderId: '216112482967',
    projectId: 'abovethebar-320b7',
    authDomain: 'abovethebar-320b7.firebaseapp.com',
    storageBucket: 'abovethebar-320b7.appspot.com',
    measurementId: 'G-4MLSY1J9MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkcU35qbYHOR5wO6Fg5EJzRxg5dcTTFb0',
    appId: '1:216112482967:android:e4ef920364173a0a5f37d2',
    messagingSenderId: '216112482967',
    projectId: 'abovethebar-320b7',
    storageBucket: 'abovethebar-320b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVkW-Qd2I5kaqsRT9Z3UNYBB02YCXuvfg',
    appId: '1:216112482967:ios:cf130b67598a56a35f37d2',
    messagingSenderId: '216112482967',
    projectId: 'abovethebar-320b7',
    storageBucket: 'abovethebar-320b7.appspot.com',
    iosClientId:
        '216112482967-11lpms47u26cr48bt73tsp1ilhpjikau.apps.googleusercontent.com',
    iosBundleId: 'com.example.aboveTheBar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVkW-Qd2I5kaqsRT9Z3UNYBB02YCXuvfg',
    appId: '1:216112482967:ios:cf130b67598a56a35f37d2',
    messagingSenderId: '216112482967',
    projectId: 'abovethebar-320b7',
    storageBucket: 'abovethebar-320b7.appspot.com',
    iosClientId:
        '216112482967-11lpms47u26cr48bt73tsp1ilhpjikau.apps.googleusercontent.com',
    iosBundleId: 'com.example.aboveTheBar',
  );
}
