# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "12.x"
      FLUTTER_VERSION: "3.7.9"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "$JAVA_VERSION"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "$FLUTTER_VERSION"
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build
      - run: flutter test
